stages:
  - install
  - build
  - test
  - deploy

cache:
  paths:
    - client/node_modules
  key: node-modules

tag_checker:
  stage: build
  script:
    - python tag_checker.py $CI_COMMIT_TAG
  only:
    - tags

install-dependencies:
  stage: install
  script:
    - cd client
    - npm install
    - cd ..

junit:
  stage: test
  script:
    - cd server
    - ./gradlew test
    
jest:
  stage: test
  script:
    - cd client
    - npm run test

dev-build:
  stage: deploy
  script:
    - cd client
    - npm run build
    - cd ../server
    - ./gradlew bootJar
    - cd ..
    - mkdir -p ../client-dev/
    - mkdir -p ../server-dev/
    - cp -r ./client/dist/ ../client-dev/
    - cp -r ./server/build/libs ../server-dev
    - fuser -k 9499/tcp 9500/tcp || if [ $? -eq 1 ]; then echo "Server was not running"; fi
    - screen -d -m /home/sengstudent/deployclienttest.sh
    - screen -d -m /home/sengstudent/deployservertest.sh
  except:
    - tags

release-build:
 stage: deploy
 script:
    - cd client
    - npm run build
    - cd ../server
    - ./gradlew bootJar
    - cd ..
    - mkdir -p ../client-prod/
    - mkdir -p ../server-prod/
    - cp -r ./client/dist/ ../client-prod/
    - cp -r ./server/build/libs ../server-prod
    - fuser -k 8999/tcp 9000/tcp || if [ $? -eq 1 ]; then echo "Server was not running"; fi
    - screen -d -m /home/sengstudent/deployclientprod.sh
    - screen -d -m /home/sengstudent/deployserverprod.sh
 artifacts:
    paths:
    - client/dist
    - server/out
 only:
    - tags
