stages:
  - install
  - build
  - test
  - deploy

cache:
  paths:
    - client/node_modules
  key: node-modules

tag_checker:
  stage: build
  script:
    - python tag_checker.py $CI_COMMIT_TAG
  only:
    - tags

install-dependencies:
  stage: install
  script:
    - cd client
    - npm install
    - cd ..

junit:
  stage: test
  script:
    - cd server
    - ./gradlew test
    
jest:
  stage: test
  script:
    - cd client
    - npm run test

deploy-test-server:
  stage: deploy
  script:
    # Create artifact
    - cd server
    - ./gradlew bootJar
    # Move artifact to clean directory
    - rm -rf /home/gitlab-runner/test-server/
    - mkdir -p /home/gitlab-runner/test-server/
    - cp -r ./build/libs /home/gitlab-runner/test-server
    # Update bash script and restart service
    - rm -f /home/gitlab-runner/runTestServer.sh || true
    - cp ../deployment-scripts/runTestServer.sh /home/gitlab-runner/runTestServer.sh
    - sed -i "s/DB_URL/$SQL_URL$SQL_TEST_DATABASE/g" runTestServer.sh
    - sed -i "s/DB_USERNAME/$SQL_USERNAME/g" runTestServer.sh
    - sed -i "s/DB_PASSWORD/$SQL_PASSWORD/g" runTestServer.sh
    - sudo systemctl restart testServer
  except:
    - tags

deploy-test-client:
  stage: deploy
  script:
    # Create artifact
    - cd client
    - npm run build
    # Move artifact to clean directory
    - rm -rf /home/gitlab-runner/test-client/
    - mkdir -p /home/gitlab-runner/test-client/
    - cp -r ./dist /home/gitlab-runner/test-client
    # Update bash script and restart service
    - rm -f /home/gitlab-runner/runTestClient.sh || true
    - cp ../deployment-scripts/runTestClient.sh /home/gitlab-runner/runTestClient.sh
    - sudo systemctl restart testClient
  except:
    - tags

deploy-prod-server:
  stage: deploy
  script:
    # Create artifact
    - cd server
    - ./gradlew bootJar
    # Move artifact to clean directory
    - rm -rf /home/gitlab-runner/prod-server/
    - mkdir -p /home/gitlab-runner/prod-server/
    - cp -r ./build/libs /home/gitlab-runner/prod-server
    # Update bash script and restart service
    - rm -f /home/gitlab-runner/runProdServer.sh || true
    - cp ../deployment-scripts/runProdServer.sh /home/gitlab-runner/runProdServer.sh
    - sed -i "s/DB_URL/$SQL_URL$SQL_PROD_DATABASE/g" runTestServer.sh
    - sed -i "s/DB_USERNAME/$SQL_USERNAME/g" runTestServer.sh
    - sed -i "s/DB_PASSWORD/$SQL_PASSWORD/g" runTestServer.sh
    - sudo systemctl restart prodServer
  only:
    refs:
      - master
  artifacts:
    paths:
    - server/out
 
deploy-prod-client:
  stage: deploy
  script:
    # Create artifact
    - cd client
    - npm run build
    # Move artifact to clean directory
    - rm -rf /home/gitlab-runner/prod-client/
    - mkdir -p /home/gitlab-runner/prod-client/
    - cp -r ./dist /home/gitlab-runner/prod-client
    # Update bash script and restart service
    - rm -f /home/gitlab-runner/runProdClient.sh || true
    - cp ../deployment-scripts/runProdClient.sh /home/gitlab-runner/runProdClient.sh
    - sudo systemctl restart prodClient
  only:
    refs:
      - master
  artifacts:
    paths:
    - client/dist
