/* MariaDB script to create the activity_types table and populate with some activity types.
 * the SQL was generated by defining the table in phpMyAdmin and then previewing the SQL.
 * should be run on the database where the table is desired.
 * TODO potentially add this to the build pipeline to have it run automatically (if table doesn't exist)
 * @author Jack van Heugten Breurkes
 */

CREATE TABLE `activity_type` (
    `activity_type_id` BIGINT(20) NOT NULL AUTO_INCREMENT ,
    `activity_type_name` VARCHAR(30) NOT NULL , PRIMARY KEY (`activity_type_id`),
    UNIQUE `activity_type_unique_names` (`activity_type_name`)
) ENGINE = InnoDB;


INSERT INTO `activity_type` (`activity_type_id`, `activity_type_name`)
VALUES
    (NULL, 'Walking'),  /* NULL id will insert the next available auto-incremented ID */
    (NULL, 'Running'),
    (NULL, 'Swimming'),
    (NULL, 'Road Biking'),
    (NULL, 'Mountain Biking'),
    (NULL, 'Scootering'),
    (NULL, 'Skateboarding');
